version: 2
jobs:
  build:
    docker:
      - image: dyoshikawa/laravel:latest
        environment:
          APP_ENV: local
          APP_KEY: base64:jRMWhl8pTIVapnvHyxOdrA6jOhFSKjj6zGhmx0NS6AM=
          DB_CONNECTION: mysql
          DB_USERNAME: root
          DB_PASSWORD: secret
          DB_DATABASE: circleci
      - image: dyoshikawa/mysql:latest
        environment:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: circleci
    steps:
      - checkout
      - run:
          name: Install Composer Packages
          command: |
            composer install
      - run:
          name: Install Dockerize
          command: |
            apk add -U wget
            wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
                && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
                && rm dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1
      - run:
          name: Wait for MySQL
          command: |
            dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: Migrate DB
          command: |
            php artisan migrate
      - run:
          name: PHPUnit
          command: |
            vendor/bin/phpunit
  deploy:
    docker:
      - image: dyoshikawa/laravel:latest
    steps:
      - checkout:
      - run:
          name: Deploy
          command: |
            echo "Do something..."

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master